Repository berry-market/backend, pull requests merged in 2025-01, with the labels that each got.

#6 [chore/bid] : 낙찰(채팅) 도메인 초기 세팅 (#3)
  bid/.gitattributes
  bid/.gitignore
  bid/build.gradle
  bid/gradle/wrapper/gradle-wrapper.jar
  bid/gradle/wrapper/gradle-wrapper.properties
  bid/gradlew
  bid/gradlew.bat
  bid/settings.gradle
  bid/src/main/java/com/berry/bid/BidApplication.java
  bid/src/main/java/com/berry/bid/application/dto/BidCreate.java
  bid/src/main/java/com/berry/bid/application/repository/BidRepositoryImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidServiceImpl.java
  bid/src/main/java/com/berry/bid/domain/entity/Bid.java
  bid/src/main/java/com/berry/bid/domain/repository/BidRepository.java
  bid/src/main/java/com/berry/bid/domain/service/BidService.java
  bid/src/main/java/com/berry/bid/infrastructure/config/WebsocketConfig.java
  bid/src/main/java/com/berry/bid/presentation/controller/ExternalController.java
  bid/src/main/java/com/berry/bid/presentation/controller/InternalController.java
  bid/src/main/java/com/berry/bid/presentation/controller/MessageController.java
  bid/src/test/java/com/berry/bid/BidApplicationTests.java
Labels: chore

#10 [postCategory] : 게시글 카테고리 전체 조회 기능 구현 (#9)
  post/src/main/java/com/berry/post/application/service/PostCategoryService.java
  post/src/main/java/com/berry/post/domain/repository/PostCategoryRepository.java
  post/src/main/java/com/berry/post/presentation/controller/PostCategoryController.java
  post/src/main/java/com/berry/post/presentation/response/postCategory/PostCategoryResponse.java
  post/src/main/resources/application.yml
Labels: feature

#16 [auth] : 공통모듈 설정 (#14)
  auth/src/main/java/com/berry/common/exceptionhandler/CustomApiException.java
  auth/src/main/java/com/berry/common/exceptionhandler/CustomApiExceptionHandler.java
  auth/src/main/java/com/berry/common/exceptionhandler/GlobalExceptionHandler.java
  auth/src/main/java/com/berry/common/response/ApiResponse.java
  auth/src/main/java/com/berry/common/response/ResCode.java
  auth/src/main/java/com/berry/common/response/ResErrorCode.java
  auth/src/main/java/com/berry/common/response/ResSuccessCode.java
Labels: chore, auth

#20 [postCategory] : 게시글 카테고리 수정 삭제 기능 구현 (#11)
  post/src/main/java/com/berry/post/application/service/PostCategoryService.java
  post/src/main/java/com/berry/post/domain/model/PostCategory.java
  post/src/main/java/com/berry/post/domain/repository/PostCategoryRepository.java
  post/src/main/java/com/berry/post/presentation/controller/PostCategoryController.java
  post/src/main/java/com/berry/post/presentation/request/postCategory/PostCategoryUpdateRequest.java
Labels: feature

#23 [auth] : 액세스토큰 재발급 기능구현 (#18)
  auth/src/main/java/com/berry/auth/application/service/AuthService.java
  auth/src/main/java/com/berry/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/berry/auth/infrastructure/client/UserClient.java
  auth/src/main/java/com/berry/auth/infrastructure/security/config/FilterConfig.java
  auth/src/main/java/com/berry/auth/infrastructure/security/jwt/JwtTokenParser.java
  auth/src/main/java/com/berry/auth/presentation/controller/InternalController.java
Labels: feature, auth

#30 [feat] : 내부용 토큰 검증 기능 구현 (#24)
  auth/src/main/java/com/berry/auth/application/dto/TokenValidResDto.java
  auth/src/main/java/com/berry/auth/application/service/AuthService.java
  auth/src/main/java/com/berry/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/berry/auth/infrastructure/security/filter/JwtFilter.java
  auth/src/main/java/com/berry/auth/infrastructure/security/jwt/JwtAuthenticationToken.java
  auth/src/main/java/com/berry/auth/infrastructure/security/jwt/JwtTokenParser.java
  auth/src/main/java/com/berry/auth/presentation/controller/InternalController.java
  auth/src/main/resources/application.yml
Labels: feature, auth

#31 [user] : 유저 관련 전체 기능 구현
  user/build.gradle
  user/src/main/java/com/berry/user/application/service/UserServiceImpl.java
  user/src/main/java/com/berry/user/domain/model/User.java
  user/src/main/java/com/berry/user/domain/repository/UserJpaRepository.java
  user/src/main/java/com/berry/user/domain/service/UserService.java
  user/src/main/java/com/berry/user/infrastructure/config/QueryDslConfig.java
  user/src/main/java/com/berry/user/infrastructure/repository/UserQueryRepository.java
  user/src/main/java/com/berry/user/presentation/controller/UserController.java
  user/src/main/java/com/berry/user/presentation/controller/UserInternalController.java
  user/src/main/java/com/berry/user/presentation/dto/request/SignUpRequest.java
  user/src/main/java/com/berry/user/presentation/dto/request/UpdateEmailRequest.java
  user/src/main/java/com/berry/user/presentation/dto/request/UpdatePasswordRequest.java
  user/src/main/java/com/berry/user/presentation/dto/response/GetInternalUserResponse.java
  user/src/main/java/com/berry/user/presentation/dto/response/GetUserDetailResponse.java
  user/src/main/java/com/berry/user/presentation/dto/response/GetUserResponse.java
Labels: feature, chore

#38 [feat/delivery] : 배송 수정, 삭제 기능 구현 (#29)
  delivery/src/main/java/com/berry/delivery/DeliveryApplication.java
  delivery/src/main/java/com/berry/delivery/application/DeliveryService.java
  delivery/src/main/java/com/berry/delivery/domain/model/Delivery.java
  delivery/src/main/java/com/berry/delivery/presentation/controller/DeliveryController.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/DeliveryDto.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/DeliveryUpdateRequest.java
Labels: feature

#33 [gateway] : 게이트웨이 기능 구현 (#1)
  auth/src/main/resources/application.yml
  gateway/src/main/java/com/berry/gateway/exception/GatewayException.java
  gateway/src/main/java/com/berry/gateway/exception/GatewayExceptionHandler.java
  gateway/src/main/java/com/berry/gateway/filter/JwtFilter.java
  gateway/src/main/java/com/berry/gateway/redis/RedisConfig.java
  gateway/src/main/java/com/berry/gateway/redis/RedisTokenRepository.java
  gateway/src/main/resources/application.yml
Labels: feature, gateway

#43 [post] 게시글 전체 조회 기능 구현 (#36)
  post/build.gradle
  post/src/main/java/com/berry/post/PostApplication.java
  post/src/main/java/com/berry/post/application/service/post/PostService.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/domain/repository/post/PostRepository.java
  post/src/main/java/com/berry/post/domain/repository/post/PostRepositoryCustom.java
  post/src/main/java/com/berry/post/domain/repository/post/PostRepositoryCustomImpl.java
  post/src/main/java/com/berry/post/infrastructure/config/QueryDslConfig.java
  post/src/main/java/com/berry/post/presentation/controller/PostController.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostResponse.java
Labels: feature

#37 [feature/bid] : 입찰 채팅 생성 기능 구현 (#7)
  bid/build.gradle
  bid/src/main/java/com/berry/bid/application/dto/BidCreate.java
  bid/src/main/java/com/berry/bid/application/dto/bid/BidCreate.java
  bid/src/main/java/com/berry/bid/application/dto/bidchat/BidChatCreate.java
  bid/src/main/java/com/berry/bid/application/model/cache/BidChat.java
  bid/src/main/java/com/berry/bid/application/repository/BidChatRepositoryImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidChatServiceImpl.java
  bid/src/main/java/com/berry/bid/domain/entity/Bid.java
  bid/src/main/java/com/berry/bid/domain/model/entity/Bid.java
  bid/src/main/java/com/berry/bid/domain/repository/BidChatRepository.java
  bid/src/main/java/com/berry/bid/domain/service/BidChatService.java
  bid/src/main/java/com/berry/bid/infrastructure/config/DataSourceConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/QuerydslConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/RedisConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/WebSocketConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/WebsocketConfig.java
  bid/src/main/java/com/berry/bid/presentation/controller/ExternalController.java
  bid/src/main/java/com/berry/bid/presentation/controller/InternalController.java
  bid/src/main/java/com/berry/bid/presentation/controller/MessageController.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidChatController.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidController.java
  bid/src/main/java/com/berry/bid/presentation/controller/internal/BidInternalController.java
Labels: feature, chore

#46 [auth] 로그아웃 기능구현 (#45)
  auth/src/main/java/com/berry/auth/application/service/AuthService.java
  auth/src/main/java/com/berry/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/berry/auth/domain/repository/AuthRepository.java
  auth/src/main/java/com/berry/auth/infrastructure/repository/RedisTokenRepository.java
  auth/src/main/java/com/berry/auth/infrastructure/security/filter/JwtFilter.java
  auth/src/main/java/com/berry/auth/presentation/controller/ExternalController.java
Labels: feature, auth

#48 [post] 게시글 단건 조회 기능 구현 (#44)
  post/src/main/java/com/berry/post/application/repository/PostRepositoryCustom.java
  post/src/main/java/com/berry/post/application/repository/PostRepositoryCustomImpl.java
  post/src/main/java/com/berry/post/application/service/post/PostService.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/domain/model/Post.java
  post/src/main/java/com/berry/post/domain/repository/PostRepository.java
  post/src/main/java/com/berry/post/domain/repository/ProductDetailsImagesRepository.java
  post/src/main/java/com/berry/post/presentation/controller/PostController.java
  post/src/main/java/com/berry/post/presentation/controller/PostServerController.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostDetailsResponse.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostListResponse.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostServerResponse.java
Labels: feature

#50 [feat/bid] : kafka로 user에게 bid chat 이벤트 전달 (#39)
  bid/build.gradle
  bid/src/main/java/com/berry/bid/application/model/dto/bidchat/BidChatCreate.java
  bid/src/main/java/com/berry/bid/application/model/event/UserEvent.java
  bid/src/main/java/com/berry/bid/application/service/BidChatServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/consumer/BidChatProducerService.java
  bid/src/main/java/com/berry/bid/domain/service/BidChatService.java
  bid/src/main/java/com/berry/bid/infrastructure/config/KafkaConsumerConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/KafkaProducerConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/model/enums/KafkaTopic.java
  bid/src/main/java/com/berry/bid/infrastructure/service/BidChatProducerServiceImpl.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidChatController.java
Labels: feature

#52 [gateway] : 게이트웨이 Config 설정 (#51)
  gateway/src/main/java/com/berry/gateway/config/GatewayCorsConfig.java
  gateway/src/main/java/com/berry/gateway/config/WebClientConfig.java
  gateway/src/main/java/com/berry/gateway/filter/JwtFilter.java
Labels: feature, gateway, refactor

#53 [post] 게시글 수정 삭제 기능 구현 (#49)
  post/src/main/java/com/berry/post/application/service/post/PostService.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/domain/model/Post.java
  post/src/main/java/com/berry/post/domain/repository/PostRepository.java
  post/src/main/java/com/berry/post/presentation/controller/PostController.java
  post/src/main/java/com/berry/post/presentation/request/Post/PostCreateRequest.java
  post/src/main/java/com/berry/post/presentation/request/Post/PostUpdateRequest.java
Labels: feature

#60 [delivery] 딜리버리 리팩토링
  delivery/build.gradle
  delivery/src/main/java/com/berry/delivery/DeliveryApplication.java
  delivery/src/main/java/com/berry/delivery/application/DeliveryService.java
  delivery/src/main/java/com/berry/delivery/domain/model/Delivery.java
  delivery/src/main/java/com/berry/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/berry/delivery/domain/repository/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/berry/delivery/domain/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/berry/delivery/presentation/controller/DeliveryController.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/DeliveryDto.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/DeliveryCreateRequest.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/DeliveryUpdateRequest.java
Labels: feature, refactor

#59 [gateway, auth] 프론트 토큰 처리를 위한 수정 (#58)
  auth/src/main/java/com/berry/auth/application/dto/LoginResDto.java
  auth/src/main/java/com/berry/auth/application/service/AuthService.java
  auth/src/main/java/com/berry/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/berry/auth/domain/repository/AuthRepository.java
  auth/src/main/java/com/berry/auth/infrastructure/repository/RedisTokenRepository.java
  auth/src/main/java/com/berry/auth/infrastructure/security/filter/LoginFilter.java
  auth/src/main/java/com/berry/auth/presentation/controller/ExternalController.java
  gateway/src/main/java/com/berry/gateway/filter/JwtFilter.java
Labels: gateway, auth, fix

#56 [post] 게시글 bid와 관련된 Kafka 설정 (#54)
  bid/src/main/java/com/berry/bid/application/service/BidChatServiceImpl.java
  bid/src/main/java/com/berry/bid/domain/service/BidChatService.java
  post/build.gradle
  post/src/main/java/com/berry/post/application/event/BidCreateEvent.java
  post/src/main/java/com/berry/post/application/event/BidEventMessage.java
  post/src/main/java/com/berry/post/application/event/BidUpdateEvent.java
  post/src/main/java/com/berry/post/application/service/consumer/PostConsumerService.java
  post/src/main/java/com/berry/post/application/service/consumer/PostConsumerServiceImpl.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/producer/PostProducerService.java
  post/src/main/java/com/berry/post/application/service/producer/PostProducerServiceImpl.java
  post/src/main/java/com/berry/post/domain/model/Post.java
  post/src/main/java/com/berry/post/domain/repository/PostRepository.java
  post/src/main/java/com/berry/post/infrastructure/config/KafkaConsumerConfig.java
  post/src/main/java/com/berry/post/infrastructure/config/KafkaProducerConfig.java
  post/src/main/java/com/berry/post/infrastructure/model/KafkaTopic.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostDetailsResponse.java
  post/src/main/resources/application.yml
Labels: feature

#61 [postCategory] 네비게이션 카테고리 조회용 api 구현 (#57)
  post/src/main/java/com/berry/post/application/service/postCategory/PostCategoryService.java
  post/src/main/java/com/berry/post/application/service/postCategory/PostCategoryServiceImpl.java
  post/src/main/java/com/berry/post/domain/repository/PostCategoryRepository.java
  post/src/main/java/com/berry/post/presentation/controller/PostCategoryController.java
  post/src/main/java/com/berry/post/presentation/response/postCategory/PostCategoryNavigationResponse.java
Labels: feature

#69 [review] 리뷰 생성 조회 기능 구현 (#62)
  post/src/main/java/com/berry/post/application/service/review/ReviewService.java
  post/src/main/java/com/berry/post/application/service/review/ReviewServiceImpl.java
  post/src/main/java/com/berry/post/domain/model/Review.java
  post/src/main/java/com/berry/post/domain/repository/PostRepository.java
  post/src/main/java/com/berry/post/domain/repository/ReviewRepository.java
  post/src/main/java/com/berry/post/presentation/controller/ReviewController.java
  post/src/main/java/com/berry/post/presentation/request/review/ReviewCreateRequest.java
  post/src/main/java/com/berry/post/presentation/response/review/ReviewGradeResponse.java
  post/src/main/java/com/berry/post/presentation/response/review/ReviewListResponse.java
  post/src/main/java/com/berry/post/presentation/response/review/ReviewProductResponse.java
Labels: feature

#67 [feat/bid] 낙찰 시 event 생성, bid 저장 (#40)
  bid/build.gradle
  bid/src/main/java/com/berry/bid/application/model/dto/bid/BidCreate.java
  bid/src/main/java/com/berry/bid/application/model/event/BidEvent.java
  bid/src/main/java/com/berry/bid/application/model/event/DeliveryEvent.java
  bid/src/main/java/com/berry/bid/application/model/event/PostEvent.java
  bid/src/main/java/com/berry/bid/application/repository/BidJpaRepository.java
  bid/src/main/java/com/berry/bid/application/repository/BidRepositoryImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidChatServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/message/BidChatConsumerService.java
  bid/src/main/java/com/berry/bid/application/service/message/BidChatProducerService.java
  bid/src/main/java/com/berry/bid/application/service/message/BidConsumerService.java
  bid/src/main/java/com/berry/bid/application/service/message/BidProducerService.java
  bid/src/main/java/com/berry/bid/domain/model/entity/Bid.java
  bid/src/main/java/com/berry/bid/domain/repository/BidRepository.java
  bid/src/main/java/com/berry/bid/domain/service/BidChatService.java
  bid/src/main/java/com/berry/bid/domain/service/BidService.java
  bid/src/main/java/com/berry/bid/infrastructure/config/DataSourceConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/KafkaConsumerConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/QuerydslConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidChatConsumerServiceImpl.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidChatProducerServiceImpl.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidConsumerServiceImpl.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidProducerServiceImpl.java
Labels: feature

#66 [user] 유저 내부 통신 관련 리팩토링
  user/build.gradle
  user/src/main/java/com/berry/user/UserApplication.java
  user/src/main/java/com/berry/user/application/service/UserServiceImpl.java
  user/src/main/java/com/berry/user/domain/model/User.java
  user/src/main/java/com/berry/user/domain/service/UserService.java
  user/src/main/java/com/berry/user/presentation/controller/AdminUserController.java
  user/src/main/java/com/berry/user/presentation/controller/UserController.java
  user/src/main/java/com/berry/user/presentation/controller/UserInternalController.java
  user/src/main/java/com/berry/user/presentation/dto/response/GetLoginUserResponse.java
Labels: refactor

#71 [review] 리뷰 수정 삭제 기능 구현 (#70)
  post/src/main/java/com/berry/post/application/service/review/ReviewService.java
  post/src/main/java/com/berry/post/application/service/review/ReviewServiceImpl.java
  post/src/main/java/com/berry/post/domain/model/Review.java
  post/src/main/java/com/berry/post/domain/repository/ReviewRepository.java
  post/src/main/java/com/berry/post/presentation/controller/ReviewController.java
  post/src/main/java/com/berry/post/presentation/request/review/ReviewUpdateRequest.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostServerResponse.java
Labels: feature

#73 [feat] 낙찰 세부내용 단건 조회 (#68)
  bid/build.gradle
  bid/src/main/java/com/berry/bid/BidApplication.java
  bid/src/main/java/com/berry/bid/application/model/dto/bid/BidView.java
  bid/src/main/java/com/berry/bid/application/repository/BidRepositoryImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidServiceImpl.java
  bid/src/main/java/com/berry/bid/domain/model/entity/Bid.java
  bid/src/main/java/com/berry/bid/domain/repository/BidRepository.java
  bid/src/main/java/com/berry/bid/domain/service/BidService.java
  bid/src/main/java/com/berry/bid/infrastructure/client/PostClient.java
  bid/src/main/java/com/berry/bid/infrastructure/common/auditor/AuditorAwareImpl.java
  bid/src/main/java/com/berry/bid/infrastructure/common/exceptionhandler/CustomApiException.java
  bid/src/main/java/com/berry/bid/infrastructure/common/exceptionhandler/CustomApiExceptionHandler.java
  bid/src/main/java/com/berry/bid/infrastructure/common/exceptionhandler/GlobalExceptionHandler.java
  bid/src/main/java/com/berry/bid/infrastructure/common/exceptionhandler/ValidExceptionHandler.java
  bid/src/main/java/com/berry/bid/infrastructure/common/response/ApiResponse.java
  bid/src/main/java/com/berry/bid/infrastructure/common/response/ResCode.java
  bid/src/main/java/com/berry/bid/infrastructure/common/response/ResErrorCode.java
  bid/src/main/java/com/berry/bid/infrastructure/common/response/ResSuccessCode.java
  bid/src/main/java/com/berry/bid/infrastructure/common/role/Role.java
  bid/src/main/java/com/berry/bid/infrastructure/common/role/RoleAspect.java
  bid/src/main/java/com/berry/bid/infrastructure/common/role/RoleCheck.java
  bid/src/main/java/com/berry/bid/infrastructure/model/dto/PostInternalView.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidController.java
Labels: feature

#75 [auth] 유저 FeignClient 연결 (#64)
  auth/src/main/java/com/berry/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/berry/auth/infrastructure/client/UserClient.java
  auth/src/main/java/com/berry/auth/infrastructure/security/dto/UserInfoResDto.java
  auth/src/main/java/com/berry/auth/infrastructure/security/dto/UserLoginResDto.java
  auth/src/main/java/com/berry/auth/infrastructure/security/service/CustomUserDetailsService.java
  gateway/src/main/java/com/berry/gateway/filter/JwtFilter.java
Labels: feature, auth

#78 [user] 유저 서비스 수정 (#77)
  user/build.gradle
  user/src/main/java/com/berry/report/presentation/controller/ReportController.java
  user/src/main/java/com/berry/user/presentation/controller/UserController.java
Labels: fix

#80 [delivery] Bid - Delivery Kafka 연결, FeignClients 셋팅
  delivery/build.gradle
  delivery/src/main/java/com/berry/delivery/DeliveryApplication.java
  delivery/src/main/java/com/berry/delivery/application/event/BidCompletionEvent.java
  delivery/src/main/java/com/berry/delivery/application/event/DeliveryStatusEvent.java
  delivery/src/main/java/com/berry/delivery/application/service/consumer/BidCompletionConsumer.java
  delivery/src/main/java/com/berry/delivery/application/service/delivery/DeliveryService.java
  delivery/src/main/java/com/berry/delivery/application/service/producer/DeliveryStatusProducer.java
  delivery/src/main/java/com/berry/delivery/presentation/controller/DeliveryController.java
  delivery/src/main/resources/application.yml
Labels: feature

#81 [post/postCategory/review] 권한 처리 추가
  post/src/main/java/com/berry/post/application/service/post/PostService.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/postCategory/PostCategoryServiceImpl.java
  post/src/main/java/com/berry/post/application/service/review/ReviewService.java
  post/src/main/java/com/berry/post/application/service/review/ReviewServiceImpl.java
  post/src/main/java/com/berry/post/presentation/controller/PostCategoryController.java
  post/src/main/java/com/berry/post/presentation/controller/PostController.java
  post/src/main/java/com/berry/post/presentation/controller/ReviewController.java
  post/src/main/java/com/berry/post/presentation/request/Post/PostCreateRequest.java
  post/src/main/java/com/berry/post/presentation/request/postCategory/PostCategoryUpdateRequest.java
Labels: feature

#83 [feat/bid] delivery event 처리, 권한 및 에러 exception 처리 로직
  bid/src/main/java/com/berry/bid/application/model/event/BidEvent.java
  bid/src/main/java/com/berry/bid/application/model/event/DeliveryEvent.java
  bid/src/main/java/com/berry/bid/application/service/BidChatServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/message/BidConsumerService.java
  bid/src/main/java/com/berry/bid/application/service/message/BidProducerService.java
  bid/src/main/java/com/berry/bid/domain/model/entity/Bid.java
  bid/src/main/java/com/berry/bid/domain/service/BidService.java
  bid/src/main/java/com/berry/bid/infrastructure/common/role/Role.java
  bid/src/main/java/com/berry/bid/infrastructure/config/KafkaConsumerConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/model/enums/KafkaTopic.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidConsumerServiceImpl.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidProducerServiceImpl.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidChatController.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidController.java
  bid/src/main/java/com/berry/common/auditor/AuditorAwareImpl.java
  bid/src/main/java/com/berry/common/exceptionhandler/CustomApiException.java
  bid/src/main/java/com/berry/common/exceptionhandler/CustomApiExceptionHandler.java
  bid/src/main/java/com/berry/common/exceptionhandler/GlobalExceptionHandler.java
  bid/src/main/java/com/berry/common/exceptionhandler/ValidExceptionHandler.java
  bid/src/main/java/com/berry/common/response/ApiResponse.java
  bid/src/main/java/com/berry/common/response/ResCode.java
  bid/src/main/java/com/berry/common/response/ResErrorCode.java
  bid/src/main/java/com/berry/common/response/ResSuccessCode.java
  bid/src/main/java/com/berry/common/role/Role.java
  bid/src/main/java/com/berry/common/role/RoleAspect.java
  bid/src/main/java/com/berry/common/role/RoleCheck.java
Labels: feature

#84 [post/review] Post-Service와 User FeignClient 연결 (#82)
  post/src/main/java/com/berry/post/application/dto/GetInternalUserResponse.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/review/ReviewServiceImpl.java
  post/src/main/java/com/berry/post/infrastructure/client/UserClient.java
  post/src/main/java/com/berry/post/presentation/controller/PostController.java
Labels: feature

#86 [like] 찜 관련 기능 개발
  post/src/main/java/com/berry/post/application/service/like/LikeService.java
  post/src/main/java/com/berry/post/application/service/like/LikeServiceImpl.java
  post/src/main/java/com/berry/post/domain/model/Like.java
  post/src/main/java/com/berry/post/domain/repository/LikeRepository.java
  post/src/main/java/com/berry/post/presentation/controller/LikeController.java
  post/src/main/java/com/berry/post/presentation/request/like/CreatePostLikeRequest.java
  post/src/main/java/com/berry/post/presentation/response/like/LikeResponse.java
Labels: feature

#95 [feat] 결제 조회 기능 구현 (#90)
  payment/src/main/java/com/berry/payment/application/dto/PaymentGetResDto.java
  payment/src/main/java/com/berry/payment/application/service/PaymentService.java
  payment/src/main/java/com/berry/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/berry/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/berry/payment/infrastructure/repository/PaymentJpaRepository.java
  payment/src/main/java/com/berry/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/berry/payment/presentation/controller/ExternalController.java
Labels: feature, payment

#96 [post] post 찜 여부 response 기능 추가 (#93)
  post/src/main/java/com/berry/post/PostApplication.java
  post/src/main/java/com/berry/post/application/service/like/LikeServiceImpl.java
  post/src/main/java/com/berry/post/application/service/post/PostService.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/domain/model/Like.java
  post/src/main/java/com/berry/post/domain/repository/LikeRepository.java
  post/src/main/java/com/berry/post/presentation/controller/PostController.java
Labels: feature

#98 [payment] 결제 완료 이벤트- 카프카 구현 #91
  payment/src/main/java/com/berry/payment/application/service/PaymentProducerService.java
  payment/src/main/java/com/berry/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/berry/payment/infrastructure/kafka/PaymentCompletedEvent.java
  payment/src/main/java/com/berry/payment/infrastructure/kafka/PaymentProducerServiceImpl.java
Labels: feature, payment

#103 [post] consumer 에러 해결 (#85)
  post/src/main/java/com/berry/post/application/model/event/BidCreateEvent.java
  post/src/main/java/com/berry/post/application/model/event/BidUpdateEvent.java
  post/src/main/java/com/berry/post/application/model/event/PostEvent.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/producer/PostProducerService.java
  post/src/main/java/com/berry/post/application/service/producer/PostProducerServiceImpl.java
  post/src/main/java/com/berry/post/infrastructure/config/KafkaConsumerConfig.java
  post/src/main/resources/application.yml
Labels: fix

#107 [Auth] ResponseEntity 제거 (#106)
  auth/src/main/java/com/berry/auth/presentation/controller/ExternalController.java
  auth/src/main/java/com/berry/auth/presentation/controller/InternalController.java
Labels: auth, refactor

#109 [post/review] userClient 호출 수정 (#104)
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/review/ReviewServiceImpl.java
  post/src/main/java/com/berry/post/infrastructure/client/UserClient.java
Labels: refactor

#113 [user] 유저 추가 기능 구현 및 리팩토링
  user/build.gradle
  user/src/main/java/com/berry/user/application/service/ReportServiceImpl.java
  user/src/main/java/com/berry/user/application/service/S3UploadService.java
  user/src/main/java/com/berry/user/application/service/UserServiceImpl.java
  user/src/main/java/com/berry/user/domain/model/Report.java
  user/src/main/java/com/berry/user/domain/model/User.java
  user/src/main/java/com/berry/user/domain/repository/UserJpaRepository.java
  user/src/main/java/com/berry/user/domain/service/UserService.java
  user/src/main/java/com/berry/user/infrastructure/config/S3Config.java
  user/src/main/java/com/berry/user/infrastructure/repository/ReportQueryRepository.java
  user/src/main/java/com/berry/user/presentation/controller/UserController.java
  user/src/main/java/com/berry/user/presentation/dto/request/CreateReportRequest.java
  user/src/main/java/com/berry/user/presentation/dto/response/ReportResponse.java
  user/src/main/resources/application.yml
Labels: feature, refactor

#115 도커 DB 통합 및 환경변수 변경, 모니터링 관련 추가 (#110)
  .gitignore
  auth/build.gradle
  auth/docker-compose.yml
  auth/src/main/resources/application.yml
  bid/build.gradle
  bid/docker-compose.yml
  delivery/build.gradle
  delivery/docker-compose.yml
  delivery/src/main/resources/application.yml
  docker-compose.yml
  eureka/build.gradle
  eureka/docker-compose.yml
  eureka/src/main/resources/application.yml
  gateway/build.gradle
  gateway/docker-compose.yml
  gateway/src/main/resources/application.yml
  init.sql
  monitoring/docker-compose.yml
  monitoring/prometheus.yml
  payment/build.gradle
  payment/docker-compose.yml
  payment/src/main/resources/application.yml
  post/build.gradle
  post/docker-compose.yml
  post/src/main/resources/application.yml
  run-all-services.sh
  user/build.gradle
  user/docker-compose.yml
  user/src/main/resources/application.yml
Labels: feature, fix

#116 [post/postCategory/review] post-service 추가 기능 구현 (#111)
  post/build.gradle
  post/src/main/java/com/berry/post/PostApplication.java
  post/src/main/java/com/berry/post/application/repository/PostRepositoryCustom.java
  post/src/main/java/com/berry/post/application/repository/PostRepositoryCustomImpl.java
  post/src/main/java/com/berry/post/application/service/post/PostService.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/postCategory/PostCategoryServiceImpl.java
  post/src/main/java/com/berry/post/application/service/review/ReviewServiceImpl.java
  post/src/main/java/com/berry/post/infrastructure/client/UserService.java
  post/src/main/java/com/berry/post/infrastructure/config/CacheConfig.java
  post/src/main/java/com/berry/post/infrastructure/config/RedisConfig.java
  post/src/main/java/com/berry/post/presentation/controller/PostController.java
  post/src/main/java/com/berry/post/presentation/response/postCategory/PostCategoryNavigationResponse.java
  post/src/main/resources/application.yml
Labels: feature, refactor

#117 [feat/bid] 입찰 삭제 메서드 추가 (#114)
  bid/src/main/java/com/berry/bid/application/service/BidChatServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidServiceImpl.java
  bid/src/main/java/com/berry/bid/domain/service/BidService.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidController.java
Labels: feature

#122 [notification] 상태 변경시 알림 생성
  delivery/build.gradle
  delivery/src/main/java/com/berry/delivery/application/event/BidCompletionEvent.java
  delivery/src/main/java/com/berry/delivery/application/event/DeliveryStatusEvent.java
  delivery/src/main/java/com/berry/delivery/application/service/consumer/BidCompletionConsumer.java
  delivery/src/main/java/com/berry/delivery/application/service/delivery/DeliveryService.java
  delivery/src/main/java/com/berry/delivery/application/service/notification/NotificationService.java
  delivery/src/main/java/com/berry/delivery/application/service/producer/DeliveryStatusProducer.java
  delivery/src/main/java/com/berry/delivery/domain/model/delivery/Delivery.java
  delivery/src/main/java/com/berry/delivery/domain/model/delivery/DeliveryStatus.java
  delivery/src/main/java/com/berry/delivery/domain/model/notification/Notification.java
  delivery/src/main/java/com/berry/delivery/domain/repository/delivery/DeliveryRepository.java
  delivery/src/main/java/com/berry/delivery/domain/repository/delivery/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/berry/delivery/domain/repository/delivery/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/berry/delivery/domain/repository/notification/NotificationRepository.java
  delivery/src/main/java/com/berry/delivery/presentation/controller/delivery/DeliveryController.java
  delivery/src/main/java/com/berry/delivery/presentation/controller/notification/NotificationController.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/DeliveryDto.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/NotificationDto.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/DeliveryCreateRequest.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/DeliveryUpdateRequest.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/delivery/DeliveryCreateRequest.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/delivery/DeliveryUpdateRequest.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/request/notification/NotificationCreateRequest.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/response/delivery/DeliverySearchResponse.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/response/notification/NotificationSearchResponse.java
Labels: feature

#126 [payment] 결제 취소 기능 구현, 결제 리팩토링 (#94)
  payment/src/main/java/com/berry/payment/application/dto/ConfirmPaymentReqDto.java
  payment/src/main/java/com/berry/payment/application/dto/PaymentGetResDto.java
  payment/src/main/java/com/berry/payment/application/dto/TossCancelReqDto.java
  payment/src/main/java/com/berry/payment/application/dto/TossCancelResDto.java
  payment/src/main/java/com/berry/payment/application/dto/TossPaymentResDto.java
  payment/src/main/java/com/berry/payment/application/event/PaymentEvent.java
  payment/src/main/java/com/berry/payment/application/service/PaymentProducerService.java
  payment/src/main/java/com/berry/payment/application/service/PaymentService.java
  payment/src/main/java/com/berry/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/berry/payment/domain/model/Payment.java
  payment/src/main/java/com/berry/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/berry/payment/infrastructure/client/TossPaymentClient.java
  payment/src/main/java/com/berry/payment/infrastructure/config/RedisConfig.java
  payment/src/main/java/com/berry/payment/infrastructure/repository/PaymentJpaRepository.java
  payment/src/main/java/com/berry/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/berry/payment/infrastructure/repository/RedisIdempotencyRepository.java
  payment/src/main/java/com/berry/payment/infrastructure/repository/RedisPaymentRepository.java
  payment/src/main/java/com/berry/payment/infrastructure/service/PaymentProducerServiceImpl.java
  payment/src/main/java/com/berry/payment/presentation/controller/PaymentController.java
Labels: feature, fix, refactor, payment

#124 [post] 게시글 전체 조회 캐싱 적용
  post/docker-compose.yml
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/postCategory/PostCategoryServiceImpl.java
  post/src/main/java/com/berry/post/infrastructure/config/CacheConfig.java
  post/src/main/java/com/berry/post/infrastructure/config/RedisConfig.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostListResponse.java
  post/src/main/resources/application.yml
  post/src/test/java/com/berry/post/application/service/post/PostServiceImplTest.java
Labels: feature, refactor

#127 [feat/bid] 입찰 페이지네이션 처리
  bid/build.gradle
  bid/src/main/java/com/berry/bid/application/model/dto/bid/BidView.java
  bid/src/main/java/com/berry/bid/application/repository/BidRepositoryImpl.java
  bid/src/main/java/com/berry/bid/application/repository/BidRespositoryCustom.java
  bid/src/main/java/com/berry/bid/application/service/BidServiceImpl.java
  bid/src/main/java/com/berry/bid/domain/model/entity/Bid.java
  bid/src/main/java/com/berry/bid/domain/repository/BidRepository.java
  bid/src/main/java/com/berry/bid/domain/service/BidService.java
  bid/src/main/java/com/berry/bid/infrastructure/client/DeliveryClient.java
  bid/src/main/java/com/berry/bid/infrastructure/model/dto/DeliveryInternalView.java
  bid/src/main/java/com/berry/bid/presentation/controller/external/BidController.java
Labels: feature

#132 [delivery] 딜리버리 테스트 코드 추가
  README.md
  delivery/build.gradle
  delivery/src/main/java/com/berry/delivery/application/service/consumer/BidCompletionConsumer.java
  delivery/src/main/java/com/berry/delivery/application/service/delivery/DeliveryService.java
  delivery/src/main/java/com/berry/delivery/domain/repository/delivery/DeliveryRepository.java
  delivery/src/main/java/com/berry/delivery/presentation/controller/delivery/DeliveryController.java
  delivery/src/main/java/com/berry/delivery/presentation/dto/response/delivery/BidStatusResponse.java
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/berry/delivery/BidCompletionConsumerTest.java
  delivery/src/test/java/com/berry/delivery/DeliveryServiceTest.java
Labels: feature, test

#136 [user] 카프카 기능 구현
  user/build.gradle
  user/src/main/java/com/berry/user/application/model/event/UserEvent.java
  user/src/main/java/com/berry/user/application/service/UserConsumerService.java
  user/src/main/java/com/berry/user/domain/model/User.java
  user/src/main/java/com/berry/user/infrastructure/config/KafkaConsumerConfig.java
  user/src/main/java/com/berry/user/infrastructure/model/PaymentEvent.java
Labels: feature

#138 [feat/bid] 카프카에서 여러 이벤트 수신 설정
  bid/src/main/java/com/berry/bid/application/model/event/BidEvent.java
  bid/src/main/java/com/berry/bid/infrastructure/config/KafkaConsumerConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/config/WebSocketConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidChatConsumerServiceImpl.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidConsumerServiceImpl.java
Labels: refactor

#133 [review] 리뷰 평점 계산 테스트 코드 작성 (#129)
  post/src/main/resources/application.yml
  post/src/test/java/com/berry/post/application/service/review/ReviewServiceImplTest.java
Labels: test

#140 [user] 유저, 찜, 신고 테스트 코드 작성
  post/src/main/java/com/berry/post/application/service/like/LikeServiceImpl.java
  post/src/test/java/com/berry/post/application/service/like/LikeServiceImplTest.java
  post/src/test/java/com/berry/post/presentation/controller/LikeControllerTest.java
  user/src/test/java/com/berry/user/application/service/ReportServiceImplTest.java
  user/src/test/java/com/berry/user/application/service/UserServiceImplTest.java
  user/src/test/java/com/berry/user/presentation/controller/ReportControllerTest.java
  user/src/test/java/com/berry/user/presentation/controller/UserControllerTest.java
Labels: refactor, test

#141 [gateway, payment, auth] 테스트코드 작성 및 자잘한 리팩토링 (#128)
  auth/src/main/java/com/berry/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/berry/auth/infrastructure/config/RedisConfig.java
  auth/src/main/java/com/berry/auth/infrastructure/repository/RedisTokenRepository.java
  auth/src/main/java/com/berry/auth/infrastructure/security/filter/JwtFilter.java
  auth/src/main/java/com/berry/auth/infrastructure/security/filter/LoginFilter.java
  auth/src/main/java/com/berry/auth/infrastructure/security/jwt/JwtTokenFactory.java
  auth/src/main/java/com/berry/auth/infrastructure/security/jwt/JwtTokenParser.java
  auth/src/main/java/com/berry/auth/infrastructure/security/jwt/JwtTokenValidator.java
  auth/src/main/java/com/berry/auth/infrastructure/security/service/CustomUserDetailsService.java
  auth/src/main/java/com/berry/auth/presentation/controller/AuthController.java
  auth/src/main/java/com/berry/auth/presentation/controller/AuthInternalController.java
  auth/src/test/java/com/berry/auth/application/service/AuthServiceImplTest.java
  docker-compose.yml
  gateway/docker-compose.yml
  gateway/src/main/java/com/berry/gateway/config/GatewayCorsConfig.java
  gateway/src/main/java/com/berry/gateway/config/WebSocketClientConfig.java
  gateway/src/main/java/com/berry/gateway/filter/JwtFilter.java
  gateway/src/main/java/com/berry/gateway/redis/RedisConfig.java
  gateway/src/main/java/com/berry/gateway/redis/RedisTokenRepository.java
  gateway/src/main/resources/application.yml
  payment/src/main/java/com/berry/payment/application/dto/ConfirmPaymentReqDto.java
  payment/src/main/java/com/berry/payment/application/dto/PaymentGetResDto.java
  payment/src/main/java/com/berry/payment/application/dto/TempPaymentReqDto.java
  payment/src/main/java/com/berry/payment/application/dto/TossCancelReqDto.java
  payment/src/main/java/com/berry/payment/application/dto/TossPaymentResDto.java
  payment/src/main/java/com/berry/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/berry/payment/domain/model/Payment.java
  payment/src/main/resources/application.yml
  payment/src/test/java/com/berry/payment/PaymentApplicationTests.java
  payment/src/test/java/com/berry/payment/application/service/PaymentServiceImplTest.java
Labels: fix, refactor, test

#146 [post] post-service 코드 수정 (#142)
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/producer/PostProducerServiceImpl.java
  post/src/main/java/com/berry/post/infrastructure/model/KafkaTopic.java
Labels: fix, refactor

#150 [post] 게시글 토픽 수정 (#142)
  post/src/main/java/com/berry/post/application/model/event/PostEvent.java
  post/src/main/java/com/berry/post/application/service/consumer/PostConsumerServiceImpl.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/application/service/producer/PostProducerService.java
  post/src/main/java/com/berry/post/application/service/producer/PostProducerServiceImpl.java
  post/src/main/java/com/berry/post/infrastructure/model/KafkaTopic.java
Labels: fix, refactor

#151 [bid] 입찰 예외 처리 및 event 처리
  bid/src/main/java/com/berry/bid/application/model/event/BidEvent.java
  bid/src/main/java/com/berry/bid/application/model/event/PostEvent.java
  bid/src/main/java/com/berry/bid/application/model/event/UserEvent.java
  bid/src/main/java/com/berry/bid/application/repository/BidChatRepositoryImpl.java
  bid/src/main/java/com/berry/bid/application/repository/BidRepositoryCustom.java
  bid/src/main/java/com/berry/bid/application/service/BidChatServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/BidServiceImpl.java
  bid/src/main/java/com/berry/bid/application/service/message/BidChatConsumerService.java
  bid/src/main/java/com/berry/bid/domain/repository/BidChatRepository.java
  bid/src/main/java/com/berry/bid/domain/service/BidChatService.java
  bid/src/main/java/com/berry/bid/infrastructure/client/UserClient.java
  bid/src/main/java/com/berry/bid/infrastructure/config/KafkaConsumerConfig.java
  bid/src/main/java/com/berry/bid/infrastructure/model/dto/UserInternalView.java
  bid/src/main/java/com/berry/bid/infrastructure/model/enums/KafkaTopic.java
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidChatConsumerServiceImpl.java
Labels: fix, refactor

#154 [bid] 카프카 토픽 명 수정, 로그 추가
  bid/src/main/java/com/berry/bid/infrastructure/service/message/BidChatConsumerServiceImpl.java
Labels: fix

#155 [post] 게시글 조회 캐싱 키 수정
  post/src/main/java/com/berry/post/application/service/like/LikeServiceImpl.java
  post/src/main/java/com/berry/post/application/service/post/PostServiceImpl.java
  post/src/main/java/com/berry/post/presentation/response/Post/PostListResponse.java
Labels: fix

#158 Zipkin 적용 및 파일 수정
  auth/build.gradle
  auth/src/main/resources/application.yml
  bid/.gitignore
  bid/build.gradle
  bid/src/main/resources/application.yml
  delivery/build.gradle
  delivery/src/main/resources/application.yml
  eureka/build.gradle
  eureka/src/main/resources/application.yml
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  payment/build.gradle
  payment/src/main/resources/application.yml
  post/build.gradle
  post/src/main/java/com/berry/post/presentation/controller/LikeController.java
  post/src/main/resources/application.yml
  user/build.gradle
  user/src/main/resources/application.yml
Labels: chore

#162 fix : 찜 전체 조회 응답값 수정 + 쿼리dsl 사용
  post/src/main/java/com/berry/post/application/repository/LikeRepositoryCustom.java
  post/src/main/java/com/berry/post/application/repository/LikeRepositoryCustomImpl.java
  post/src/main/java/com/berry/post/application/service/like/LikeServiceImpl.java
  post/src/main/java/com/berry/post/presentation/response/like/LikeResponse.java
Labels: fix
